set encoding=utf-8
scriptencoding utf-8

source $VIMRUNTIME/defaults.vim

syntax enable

set autoindent
set backspace=indent,eol,start
set colorcolumn=80
set expandtab
set exrc " load additional rc from cwd
set linebreak
set number
set sm " matching braces
set smartcase
set tabstop=4
set ttyfast

set showbreak=↪\
set listchars=eol:↲,tab:⇢\ ,trail:·,extends:>,precedes:<,space:·

set mouse=v

au BufRead,BufNewFile *.nix set filetype=nix
autocmd FileType nix setlocal shiftwidth=2 softtabstop=2 expandtab
autocmd FileType markdown,text set nonumber

" map `w!!` for when we forgot to open with sudo
cmap w!! %!sudo tee > /dev/null %

let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1
let g:show_spaces_that_precede_tabs=1

" Ctrl-P to fuzzy find files
nnoremap <C-p> :Files<CR>
" Ctrl-B to switch between open buffers
nnoremap <C-b> :Buffers<CR>
" Ctrl-F to search in files
nnoremap <C-f> :Rg<CR>
