set encoding=utf-8
scriptencoding utf-8

syntax enable

set notermguicolors
set autoindent
set backspace=indent,eol,start
set colorcolumn=80
set expandtab
set exrc " load additional rc from cwd
set linebreak
set number
set sm " matching braces
set smartcase
set tabstop=4
set ttyfast

set showbreak=↪\
set listchars=eol:↲,tab:⇢\ ,trail:·,extends:>,precedes:<,space:·

set mouse=v

autocmd FileType nix setlocal shiftwidth=2 softtabstop=2 expandtab
autocmd FileType markdown,text set nonumber

" map `w!!` for when we forgot to open with sudo
cmap w!! %!sudo tee > /dev/null %

let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1
let g:show_spaces_that_precede_tabs=1

lua << EOF
vim.lsp.config('nil_ls', {})
vim.lsp.enable('nil_ls')
vim.lsp.config('svelte', {})
vim.lsp.enable('svelte')
vim.lsp.config('ts_ls', {})
vim.lsp.enable('ts_ls')
vim.lsp.config('cssls', {})
vim.lsp.enable('cssls')
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-p>', builtin.find_files, {})
vim.keymap.set('n', '<C-b>', builtin.buffers, {})
vim.keymap.set('n', '<C-f>', builtin.live_grep, {})
EOF
